apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-maven-app-231058002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-maven-app-231058002
  template:
    metadata:
      labels:
        app: my-maven-app
    spec:
      containers:
        - name: my-maven-app-container
          image: your-docker-image:tag
          ports:
            - containerPort: 8080
