apiVersion: v1
kind: Service
metadata:
  name: my-maven-app-service-231058002
spec:
  selector:
    app: my-maven-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
